apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "agent.fullname" . }}
  annotations:
    {{- include "agent.annotations" . | nindent 4 }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.agent.updateStrategy }}
  updateStrategy: {{ . | toYaml | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- include "agent.annotations" . | nindent 8 }}
        {{- with .Values.agent.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "agent.labels" . | nindent 8 }}
        {{- with .Values.agent.podLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.agent.serviceAccount.create }}
      serviceAccountName: {{ template "agent.serviceAccountName" . }}
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.agent.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.extraInitContainers }}
      initContainers: {{ . | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: ebpf-agent
        image: {{ include "image" .Values.agent.image }}
        imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
        args:
          - -target-addr
          - "{{ template "processing.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.processing.service.port }}"
        env:
        {{- with .Values.agent.extraEnvs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.agent.livenessProbe }}
        livenessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.agent.readinessProbe }}
        readinessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.agent.lifecycle }}
        lifecycle: {{ . | toYaml | nindent 10 }}
        {{- end }}
        securityContext:
        {{- if .Values.agent.securityContext }}
        {{- .Values.agent.securityContext | toYaml | nindent 10 }}
        {{- else }}
        {{ include "wallarm-oob.agentSecurityContext" . | nindent 10 }}
        {{- end }}
        {{- with .Values.agent.resources }}
        resources: {{ . | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /hostproc
        {{- with .Values.agent.extraVolumeMounts }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.agent.extraContainers }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      {{- with .Values.agent.extraVolumes }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}