{{- if .Values.aggregation.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aggregation.serviceAccountName" . }}
  annotations:
    {{- include "aggregation.annotations" . | nindent 4 }}
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
    {{- with .Values.aggregation.serviceAccount.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "aggregation.labels" . | nindent 4 }}
{{- end -}}
